### ISSUE TITLE
Make output systematic either by rounding off the result or by making textview adaptive

### ISSUE THREAD

**Issue by anant-dev** [justudin/simple-calc#8]
if we multiply two decimal number the result looks like : 
![pic1](https://cloud.githubusercontent.com/assets/13196029/19938027/84cdc25e-a149-11e6-82b2-e8fec89e7a25.png)

to get actual result we need to scroll it to the right :
![pic2](https://cloud.githubusercontent.com/assets/13196029/19938047/a353160c-a149-11e6-92b2-f92958a25d94.png)

need to improve the UI for easy understanding

**Comment by justudin** [comment]
Hi @anant-dev! Thanks for the issue.
I've tried to solve the issue by changing the field size and make it fixed `setFixedWidth(150)` for each inputs fields and result field. I guess it's solved the issue.
